### ISSUE TITLE
Libssl.so.1.1 not found on ubuntu 22.04 LTS (bitswap-monitor-client)

### ISSUE THREAD

**Issue by lgehr** [mrd0ll4r/ipfs-tools#22]
If I download the current release and try to run it on Ubuntu 22.04 TLS I get

`./bin/bitswap-monitor-client: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
`

**Comment by mrd0ll4r** [comment]
Fixed via #24 :)
